import os


DEBUG = True

SERVER_DOMAIN = ''
DATABASE_KEY = ''
SECRET_KEY = ''

MYSQL_SERVER = ''
MYSQL_DATABASE = ''
MYSQL_USER = ''
MYSQL_PASSWORD = ''

SQLALCHEMY_DATABASE_URI = os.getenv(
    'SQLALCHEMY_DATABASE_URI',
    'mysql+pymysql://{}:{}@{}/{}?charset=utf8'.format(MYSQL_USER, MYSQL_PASSWORD, MYSQL_SERVER, MYSQL_DATABASE)
)
SQLALCHEMY_TRACK_MODIFICATIONS = False
